package controller;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.event.ActionEvent;

import javafx.scene.control.Label;

import javafx.scene.layout.FlowPane;

import javafx.scene.control.ComboBox;

import javafx.scene.control.RadioButton;

public class ActivarBorrarAvionController {
	@FXML
	private Label lblTitulo;
	@FXML
	private FlowPane flowActivar;
	@FXML
	private RadioButton rbtnActivado;
	@FXML
	private RadioButton rbtnDesactivado;
	@FXML
	private Button btnGuardar_Borrar;
	@FXML
	private Button btnCancelar;
	@FXML
	private ComboBox cmbAeropuertos;
	@FXML
	private ComboBox cmbAviones;

	// Event Listener on Button[#btnGuardar_Borrar].onAction
	@FXML
	public void guardarBorrar(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnCancelar].onAction
	@FXML
	public void cancelar(ActionEvent event) {
		// TODO Autogenerated
	}
}
