package controller;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.ToggleGroup;

import javafx.scene.control.TextField;

import javafx.event.ActionEvent;

import javafx.scene.control.RadioButton;

public class AniadirAeropuertoController {
	@FXML
	private RadioButton rbtnPublico;
	@FXML
	private ToggleGroup group1;
	@FXML
	private RadioButton rbtnPrivado;
	@FXML
	private Button btnGuardar;
	@FXML
	private Button btnCancelar;
	@FXML
	private TextField txtNombre;
	@FXML
	private TextField txtPais;
	@FXML
	private TextField txtCiudad;
	@FXML
	private TextField txtCalle;
	@FXML
	private TextField txtNumero;
	@FXML
	private TextField txtInaguracion;
	@FXML
	private TextField txtCapacidad;
	@FXML
	private TextField txtFinanciacion;
	@FXML
	private TextField txtTrabajadores;

	// Event Listener on Button[#btnGuardar].onAction
	@FXML
	public void guardar(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnCancelar].onAction
	@FXML
	public void cancelar(ActionEvent event) {
		// TODO Autogenerated
	}
}
