package controller;

import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.Alert;
import javafx.scene.control.Button;

import javafx.scene.control.TextField;
import model.Login;
import dao.LoginDAO;
import javafx.event.ActionEvent;

import javafx.scene.control.PasswordField;

public class LoginController {
	@FXML
	private Button btnLogin;
	@FXML
	private PasswordField txtPassword;
	@FXML
	private TextField txtUsuario;
	
	private LoginDAO dao;
	
	private Login login;

	// Event Listener on Button[#btnLogin].onAction
	@FXML
	public void login(ActionEvent event) {
		// TODO Autogenerated
		
		login = new Login(txtUsuario.getText(), txtPassword.getText());
		dao = new LoginDAO();
		
		try {
			if(dao.validarLogin(login)) {
				Alert alert = new Alert(Alert.AlertType.INFORMATION);
				alert.setHeaderText(null);
				alert.setTitle("Error");
				alert.setContentText("bien");
				alert.showAndWait();
				
			}
			
	
			
		} catch (Exception e) {
			// TODO: handle exception
			Alert alert = new Alert(Alert.AlertType.ERROR);
			alert.setHeaderText(null);
			alert.setTitle("Error");
			alert.setContentText("Usuario y Contraseña no validos");
			alert.showAndWait();
		}
		
		
	}

	
	
}
