package controller;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.fxml.Initializable;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Alert;
import javafx.scene.control.Button;

import javafx.scene.control.TextField;
import javafx.stage.Modality;
import javafx.stage.Stage;
import model.Login;
import dao.LoginDAO;
import javafx.event.ActionEvent;

import javafx.scene.control.PasswordField;

public class LoginController {
	@FXML
	private Button btnLogin;
	@FXML
	private PasswordField txtPassword;
	@FXML
	private TextField txtUsuario;

	private LoginDAO dao;

	private Login login;

	// Event Listener on Button[#btnLogin].onAction
	@FXML
	public void login(ActionEvent event) {
		// TODO Autogenerated

		login = new Login(txtUsuario.getText(), txtPassword.getText());
		dao = new LoginDAO();
		Stage stage = (Stage) btnLogin.getScene().getWindow();

		try {
			if (dao.validarLogin(login)) {

				Alert alert = new Alert(Alert.AlertType.INFORMATION);
				alert.setHeaderText(null);
				alert.setTitle("Conexion");
				alert.setContentText("Conexion correcta");
				alert.showAndWait();

				FXMLLoader loader = new FXMLLoader(getClass().getResource("/fxml/Aeropuerto.fxml"));
				Parent root;
				try {
					root = loader.load();
					Scene newScene = new Scene(root);
					Stage newStage = new Stage();

					newStage.initModality(Modality.APPLICATION_MODAL);
					Stage myStage = (Stage) this.btnLogin.getScene().getWindow();
					newStage.initOwner(myStage);
					newStage.setScene(newScene);

					stage.hide();

					newStage.showAndWait();

					stage.close();

				} catch (Exception e) {
					// TODO: handle exception
				}
			}

		} catch (Exception e) {
			// TODO: handle exception
			Alert alert = new Alert(Alert.AlertType.ERROR);
			alert.setHeaderText(null);
			alert.setTitle("Error");
			alert.setContentText("Usuario y Contraseña no validos");
			alert.showAndWait();
		}

	}

}
