package controller;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import javafx.event.ActionEvent;

import javafx.scene.control.PasswordField;

public class LoginController {
	@FXML
	private Button btnLogin;
	@FXML
	private PasswordField txtPassword;
	@FXML
	private TextField txtUsuario;

	// Event Listener on Button[#btnLogin].onAction
	@FXML
	public void login(ActionEvent event) {
		// TODO Autogenerated
	}
}
