package controller;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.event.ActionEvent;

public class EjemploInformesController {
	@FXML
	private Button btnInforme;

	// Event Listener on Button[#btnInforme].onAction
	@FXML
	public void abrirInforme(ActionEvent event) {
		// TODO Autogenerated
	}
}
