package controller;

import javafx.fxml.FXML;
import javafx.scene.control.Alert;
import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import javafx.scene.control.ToggleGroup;
import javafx.stage.Stage;
import model.Olimpiada;

import java.time.LocalDate;

import javafx.event.ActionEvent;

import javafx.scene.control.RadioButton;

public class AniadirOlimpiadaController {
	@FXML
	private TextField txtAnio;
	@FXML
	private TextField txtCiudad;
	@FXML
	private Button btnAceptar;
	@FXML
	private Button btnCancelar;
	@FXML
	private RadioButton rbtnVerano;
	@FXML
	private ToggleGroup estaciones;
	@FXML
	private RadioButton rbtnInvierno;
	
	private Olimpiada o;
	

	// Event Listener on Button[#btnAceptar].onAction
	@FXML
	public void aceptar(ActionEvent event) {
		// TODO Autogenerated
		LocalDate current_date;
		current_date = LocalDate.now();
		int current_Year = current_date.getYear();		
				
				
		String ciudad = txtCiudad.getText();
		int anio = 0;
		String error = "";
		String temporada;
		int id = 0;
		
		if(rbtnVerano.isSelected())
			temporada = "Summer";
		else
			temporada = "Winter";
		
		
		if(ciudad.isEmpty()) {
			error += "\n El campo Ciudad no puede estar vacio";
		}
		try {
			anio = Integer.parseInt (txtAnio.getText());
			if(anio > current_Year || anio < 0) {
				error += "\n Año fuera de rango";
			}
		} catch (Exception e) {
			error += "\n La Fecha tiene que ser un entero";
		}
		
		String nombre = "\"" + anio + " " + temporada + "\"";
		
		if(error.equals("")) {
			o = new Olimpiada(id, nombre, anio, temporada, ciudad);

			Stage myStage =(Stage) this.btnCancelar.getScene().getWindow();
			myStage.close();
		}
		else {
			Alert alert = new Alert(Alert.AlertType.ERROR);
			alert.setHeaderText(null);
			alert.setTitle("Error");
			alert.setContentText(error);
			alert.showAndWait();
		}
		
		
	}
	// Event Listener on Button[#btnCancelar].onAction
	@FXML
	public void cancelar(ActionEvent event) {
		// TODO Autogenerated
		Stage myStage =(Stage) this.btnCancelar.getScene().getWindow();
		myStage.close();
	}
	
	public Olimpiada getOlimpiada(){
		return o;
	}
	
	
	
	
}
