package controller;

import javafx.fxml.FXML;
import javafx.scene.control.Alert;
import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import javafx.scene.control.ToggleGroup;
import javafx.stage.Stage;
import model.Deportista;
import model.Olimpiada;

import java.sql.SQLException;

import dao.DeporteDAO;
import dao.DeportistaDAO;
import javafx.event.ActionEvent;

import javafx.scene.control.RadioButton;

public class AniadirDeportistaController {
	@FXML
	private TextField txtNombre;
	@FXML
	private TextField txtPeso;
	@FXML
	private TextField txtAltura;
	@FXML
	private Button btnAceptar;
	@FXML
	private Button btnCancelar;
	@FXML
	private RadioButton rbtnMasculino;
	@FXML
	private ToggleGroup sexo;
	@FXML
	private RadioButton rbtnFemenino;
	
	private Deportista d;
	private DeportistaDAO existe; 

	// Event Listener on Button[#btnAceptar].onAction
	@FXML
	public void aceptar(ActionEvent event) {
		// TODO Autogenerated
		
		int id = 0;
		String nombre = txtNombre.getText();
		String sexo;
		int peso = 0;
		int altura = 0;
		String error = "";
		
		if(rbtnMasculino.isSelected()) 
			sexo = "M";
		else
			sexo = "F";

		if(nombre.isEmpty()) {
			error += "\n El campo Nombre no puede estar vacio";
		}
		
		try {
			peso = Integer.parseInt (txtPeso.getText());
			if(peso > 500 || peso < 30) {
				error += "\n Peso fuera de rango";
			}
		} catch (Exception e) {
			error += "\n El Peso tiene que ser un entero";
		}
		
		try {
			altura = Integer.parseInt (txtAltura.getText());
			if(altura > 250 || altura < 120) {
				error += "\n Altura fuera de rango. Tiene que ir en cm";
			}
		} catch (Exception e) {
			error += "\n La Altura tiene que se un entero en cm";
		}
		
		d = new Deportista(id, nombre, sexo, peso, altura);
		
		try {
			existe = new DeportistaDAO();
			if(existe.existeDeportista(d) == true)
				error += "\n Deportista ya existente";
			
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		
		if(error.equals("")) {
			
			try {
				existe.insertDeportista(d);
				
				Alert alert = new Alert(Alert.AlertType.INFORMATION);
				alert.initOwner(this.btnAceptar.getScene().getWindow());
				alert.setHeaderText(null);
				alert.setTitle("Info");
				alert.setContentText("Deportista agregada correctamente");
				alert.showAndWait();

				Stage myStage =(Stage) this.btnCancelar.getScene().getWindow();
				myStage.close();
			} catch (Exception e) {
				// TODO: handle exception
			}
		}
		else {
			Alert alert = new Alert(Alert.AlertType.ERROR);
			alert.setHeaderText(null);
			alert.setTitle("Error");
			alert.setContentText(error);
			alert.showAndWait();
		}
		
	}
	// Event Listener on Button[#btnCancelar].onAction
	@FXML
	public void cancelar(ActionEvent event) {
		// TODO Autogenerated
		
		Stage myStage =(Stage) this.btnCancelar.getScene().getWindow();
		myStage.close();
	}
	
	public Deportista getDeportista() {
		return d;
	}
}
