package controller;

import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import javafx.scene.control.ToggleGroup;
import model.Deportista;
import model.Evento;
import model.Olimpiada;

import java.net.URL;
import java.sql.SQLException;
import java.util.ResourceBundle;

import dao.DeportistaDAO;
import dao.EventoDAO;
import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import javafx.event.ActionEvent;

import javafx.scene.control.ListView;

import javafx.scene.control.RadioButton;

public class GestionarDeportistaController implements Initializable {
	@FXML
	private TextField txtNombre;
	@FXML
	private TextField txtPeso;
	@FXML
	private TextField txtAltura;
	@FXML
	private Button btnEditar;
	@FXML
	private Button btnBorrar;
	@FXML
	private Button btnCancelar;
	@FXML
	private RadioButton rbtnMasculino;
	@FXML
	private ToggleGroup sexo;
	@FXML
	private RadioButton rbtnFemenino;
	@FXML
	private ListView listDeportistas;
	
	private ObservableList<Deportista> deportistas;
	private DeportistaDAO cargarDeportistas;

	// Event Listener on Button[#btnEditar].onAction
	@FXML
	public void editar(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnBorrar].onAction
	@FXML
	public void borrar(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnCancelar].onAction
	@FXML
	public void cancelar(ActionEvent event) {
		// TODO Autogenerated
	}
	@Override
	public void initialize(URL arg0, ResourceBundle arg1) {
		// TODO Auto-generated method stub
		
		deportistas = FXCollections.observableArrayList();

		try {
			cargarDeportistas = new DeportistaDAO();
			deportistas.addAll(cargarDeportistas.selectDeportista());
			listDeportistas.setItems(deportistas);

		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		
	}
}
