package controller;

import javafx.fxml.FXML;

import javafx.scene.control.ToggleGroup;

import javafx.event.ActionEvent;

import javafx.scene.control.RadioButton;

public class Informe2Controller {
	@FXML
	private RadioButton rbtnInforme;
	@FXML
	private ToggleGroup radio;
	@FXML
	private RadioButton rbtnInformeCalculos;
	@FXML
	private RadioButton rbtnInformeSubinformes;

	// Event Listener on RadioButton[#rbtnInforme].onAction
	@FXML
	public void persona(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on RadioButton[#rbtnInformeCalculos].onAction
	@FXML
	public void calculos(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on RadioButton[#rbtnInformeSubinformes].onAction
	@FXML
	public void subinfomre(ActionEvent event) {
		// TODO Autogenerated
	}
}
