package controller;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.fxml.Initializable;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Alert;
import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import java.io.IOException;
import java.net.URL;
import java.util.ResourceBundle;

import javafx.event.ActionEvent;

import javafx.scene.control.Label;

import javafx.scene.layout.FlowPane;
import javafx.stage.Modality;
import javafx.stage.Stage;
import javafx.scene.input.MouseEvent;

import javafx.scene.control.TableView;

import javafx.scene.control.TableColumn;

public class EjercicioGController implements Initializable{
	@FXML
	private Label lbFiltrar;
	@FXML
	private TextField txtFiltrar;
	@FXML
	private Button btnImportar;
	@FXML
	private Button btnExportar;
	@FXML
	private TableView table;
	@FXML
	private TableColumn colNombre;
	@FXML
	private TableColumn colApellido;
	@FXML
	private TableColumn colEdad;
	@FXML
	private FlowPane flow1;
	@FXML
	private Button btnAgregar;
	@FXML
	private Button btnModificar;
	@FXML
	private Button btnEliminar;

	// Event Listener on Button[#btnImportar].onAction
	@FXML
	public void importar(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnExportar].onAction
	@FXML
	public void exportar(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on TableView[#table].onMouseClicked
	@FXML
	public void seleccionar(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnAgregar].onAction
	@FXML
	public void agregrar(ActionEvent event) {
		// TODO Autogenerated
		try {
			FXMLLoader loader = new FXMLLoader(getClass().getResource("/fxml/AgregrarPersonaEjer6.fxml"));
	          Parent root = loader.load();
	          Scene newScene = new Scene(root);
	          Stage newStage = new Stage();
	          newStage.initModality(Modality.APPLICATION_MODAL);
	          newStage.initOwner(this.btnAgregar.getScene().getWindow());
	          newStage.setTitle("Nueva Persona");
	          newStage.show();
	          newStage. showAndWait ();
		} catch (IOException e) {
			// TODO: handle exception
			Alert alert = new Alert(Alert.AlertType.ERROR);
	          alert.setHeaderText(null);
	          alert.setTitle("Error");
	          alert.setContentText(e.getMessage());
	          alert.showAndWait();
		}
	}
	// Event Listener on Button[#btnModificar].onAction
	@FXML
	public void modificar(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnEliminar].onAction
	@FXML
	public void eliminar(ActionEvent event) {
		// TODO Autogenerated
	}
	@Override
	public void initialize(URL arg0, ResourceBundle arg1) {
		// TODO Auto-generated method stub
		
	}
}
