package controller;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.fxml.Initializable;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Alert;
import javafx.scene.control.Button;
import javafx.collections.FXCollections;
import javafx.scene.control.TextField;
import javafx.scene.control.cell.PropertyValueFactory;

import java.io.IOException;
import java.net.URL;
import java.util.ResourceBundle;

import javafx.collections.ObservableList;
import javafx.event.ActionEvent;

import javafx.scene.control.Label;

import javafx.scene.layout.FlowPane;
import javafx.stage.Modality;
import javafx.stage.Stage;
import model.Persona;
import javafx.scene.input.MouseEvent;

import javafx.scene.control.TableView;

import javafx.scene.control.TableColumn;

public class EjercicioGController implements Initializable{
	@FXML
	private Label lbFiltrar;
	@FXML
	private TextField txtFiltrar;
	@FXML
	private Button btnImportar;
	@FXML
	private Button btnExportar;
	@FXML
	private TableView <Persona> table;
	@FXML
	private TableColumn<Persona, String> colNombre;
	@FXML
	private TableColumn<Persona, String> colApellido;
	@FXML
	private TableColumn<Persona, String> colEdad;
	@FXML
	private FlowPane flow1;
	@FXML
	private Button btnAgregar;
	@FXML
	private Button btnModificar;
	@FXML
	private Button btnEliminar;
	
	private ObservableList<Persona> personas;

	private Persona p;
	
	private int posicion;
	

	// Event Listener on Button[#btnImportar].onAction
	@FXML
	public void importar(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnExportar].onAction
	@FXML
	public void exportar(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on TableView[#table].onMouseClicked
	@FXML
	public void seleccionar(MouseEvent event) {
		// TODO Autogenerated
		if (table.getSelectionModel().getSelectedItem() != null) {
			posicion = table.getSelectionModel().getSelectedIndex();
			btnModificar.setDisable(false);
			btnEliminar.setDisable(false);
			p = table.getSelectionModel().getSelectedItem();
		}
		
		
		
	}
	// Event Listener on Button[#btnAgregar].onAction
	@FXML
	public void agregrar(ActionEvent event) {
		// TODO Autogenerated
		try {
			FXMLLoader loader = new FXMLLoader(getClass().getResource("/fxml/AgregrarPersonaEjerG.fxml"));
	          Parent root = loader.load();
	          AgregrarPersonaEjerGController controller = loader.getController();
	          Scene newScene = new Scene(root);
	          Stage newStage = new Stage();
	          newStage.initModality(Modality.APPLICATION_MODAL);
	          Stage myStage = (Stage) this.btnAgregar.getScene().getWindow();
	          newStage.initOwner(myStage);
	          newStage.setScene(newScene);
	          newStage.setTitle("Nueva Persona");
	          newStage. showAndWait ();
	          
	          p = controller.getPersona();
	          
				if (!personas.contains(p)) {
					personas.add(p);
				}
				else {
					Alert alert= new Alert(Alert.AlertType.ERROR);
					alert.initOwner(this.btnAgregar.getScene().getWindow());
					alert.setHeaderText(null);
					alert.setTitle("ERROR");
					alert.setContentText("Esa persona ya existe");
					alert.showAndWait();
				}
	          
		} catch (IOException e) {
			// TODO: handle exception
			Alert alert = new Alert(Alert.AlertType.ERROR);
	          alert.setHeaderText(null);
	          alert.setTitle("Error");
	          alert.setContentText(e.getMessage());
	          alert.showAndWait();
		}
	}
	// Event Listener on Button[#btnModificar].onAction
	@FXML
	public void modificar(ActionEvent event) {
		// TODO Autogenerated
		try {
			FXMLLoader loader = new FXMLLoader(getClass().getResource("/fxml/AgregrarPersonaEjer6.fxml"));
	          Parent root = loader.load();
	          Scene newScene = new Scene(root);
	          Stage newStage = new Stage();
	          newStage.initModality(Modality.APPLICATION_MODAL);
	          newStage.initOwner(this.btnAgregar.getScene().getWindow());
	          newStage.setScene(newScene);
	          newStage.setTitle("Modificar Persona");
	          newStage. showAndWait ();
		} catch (IOException e) {
			// TODO: handle exception
			Alert alert = new Alert(Alert.AlertType.ERROR);
	          alert.setHeaderText(null);
	          alert.setTitle("Error");
	          alert.setContentText(e.getMessage());
	          alert.showAndWait();
		}
	}
	// Event Listener on Button[#btnEliminar].onAction
	@FXML
	public void eliminar(ActionEvent event) {
		// TODO Autogenerated
		Persona p = table.getSelectionModel().getSelectedItem();
		personas.remove(p);
		
		Alert alert = new Alert(Alert.AlertType.INFORMATION);
		alert.initOwner(this.btnEliminar.getScene().getWindow());
		alert.setHeaderText(null);
		alert.setTitle("Info");
		alert.setContentText("Persona eliminada correctamente");
		alert.showAndWait();
		btnModificar.setDisable(true);
		btnEliminar.setDisable(true);
	}
	@Override
	public void initialize(URL arg0, ResourceBundle arg1) {
		// TODO Auto-generated method stub
		personas = FXCollections.observableArrayList();
		table.setItems(personas);
		colNombre.setCellValueFactory(new PropertyValueFactory<Persona, String>("nombre"));
		colApellido.setCellValueFactory(new PropertyValueFactory<Persona, String>("apellido"));
		colEdad.setCellValueFactory(new PropertyValueFactory<Persona, String>("edad"));
		btnModificar.setDisable(true);
		btnEliminar.setDisable(true);	
		
	}
}
